### ISSUE TITLE
becmodel bails on high elevation merges 

### ISSUE THREAD

**Issue by smnorris** [smnorris/becmodel#53]
```
Traceback (most recent call last):
  File "W:\FOR\VIC\HRE\Projects\Landscape\ProvBGC\CurrentWork\TestingNewBECmodel2019\becmodel\becenv\Scripts\becmodel-script.py", line 11, in <module>
    load_entry_point('becmodel', 'console_scripts', 'becmodel')()
  File "W:\FOR\VIC\HRE\Projects\Landscape\ProvBGC\CurrentWork\TestingNewBECmodel2019\becmodel\becenv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "W:\FOR\VIC\HRE\Projects\Landscape\ProvBGC\CurrentWork\TestingNewBECmodel2019\becmodel\becenv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "W:\FOR\VIC\HRE\Projects\Landscape\ProvBGC\CurrentWork\TestingNewBECmodel2019\becmodel\becenv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "W:\FOR\VIC\HRE\Projects\Landscape\ProvBGC\CurrentWork\TestingNewBECmodel2019\becmodel\becenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "w:\for\vic\hre\projects\landscape\provbgc\currentwork\testingnewbecmodel2019\becmodel\becmodel\cli.py", line 54, in cli
    BM.postfilter()
  File "w:\for\vic\hre\projects\landscape\provbgc\currentwork\testingnewbecmodel2019\becmodel\becmodel\main.py", line 742, in postfilter
    if len(self.high_elevation_types) >= 1:
  File "w:\for\vic\hre\projects\landscape\provbgc\currentwork\testingnewbecmodel2019\becmodel\becmodel\main.py", line 352, in high_elevation_types
    return list(set([k["type"] for k in self.high_elevation_merges]))
  File "w:\for\vic\hre\projects\landscape\provbgc\currentwork\testingnewbecmodel2019\becmodel\becmodel\main.py", line 342, in high_elevation_merges
    "becvalue_target": self.becvalue_lookup[high[0]],
IndexError: list index out of range
```

**Comment by smnorris** [comment]
Can't reproduce on my machine (but I have a fresh conda environment with all latest requirements)
